### PR TITLE
Fix: Return if value in setter is undefined or not, rather than the v…

### PR DESCRIPTION
**Pull request by joshuef**
…alue.

To avoid a false/fail return for setter when setting falsy values

### CODE REVIEW

**Comment by joshuef** [comment]
I see the failure. Taking a look at this 👍 (not sure if you have any idea there?)

**Comment by addaleax** [comment]
> So then I wonder, perhaps the correct thing is to simply return `true` for the setter?

Yeah, I think that’s the easiest approach :)

**Comment by addaleax** [comment]
Released in v1.0.3, let me know if you run into anything else!

**Comment by joshuef** [comment]
Great stuff. Thanks for the rapid merge, @addaleax  👍

**Pull request merged**
